target-version = "py314"
line-length = 100
src = ["packages", "apps"]

[lint]
select = ["E", "F", "I", "UP", "B"]

[lint.per-file-ignores]
"**/tests/**" = ["B018", "E501"]
"**/rest/routers/**" = ["B008"]
"**/rest/app.py" = ["B008"]
